In [8]:
# import numpy library
import numpy as np
print(np.__version__)

1.24.4


In [5]:
# Create a numpy array
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [9]:
# Check the type of the array
type(a)

numpy.ndarray

In [10]:
# Check the type of the values stored in numpy array
a.dtype

dtype('int32')

In [4]:
# Print each element
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


##### We can change the value of the array. Consider the array c

In [13]:
# Create numpy array
c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [14]:
# Assign the first element to 100
c[0] = 100
c

array([100,   1,   2,   3,   4])

In [15]:
# Set the fourth element and fifth element to 300 and 400
c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [16]:
# We can also define the steps in slicing, like this: [start:end:step]
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [17]:
# If we don't pass start its considered 0
print(arr[:4])

[1 2 3 4]


In [18]:
# If we don't pass end it considers till the length of array
print(arr[4:])

[5 6 7]


In [19]:
# If we don't pass step its considered 1
print(arr[1:5:])

[2 3 4 5]


##### Similarly, we can use a list to select more than one specific index

In [23]:
c = np.array([20, 1, 2, 3, 4])
d = c[1:4]

# Create the index list
select = [0, 2, 3, 4]
select

# Use List to select elements
d = c[select]
print(d)

# Assign the specified elements to new value
c[select] = 100000
print(c)

[20  2  3  4]
[100000      1 100000 100000 100000]


##### Basic array attributes using the array a

In [24]:
a = np.array([0, 1, 2, 3, 4])
a.size

5

In [25]:
# Get the number of dimensions of numpy array
a.ndim

1

In [26]:
# Get the shape/size of numpy array
# The attribute shape is a tuple of integers indicating the size of the array 
# in each dimension
a.shape

(5,)

##### Numpy Statistical Functions

In [27]:
a = np.array([1, -1, 1, -1])
# Get the mean of numpy array
mean = a.mean()
mean

0.0

In [28]:
# Get the standard deviation of numpy array
standard_deviation=a.std()
standard_deviation

1.0

In [30]:
b = np.array([-1, 2, 3, 4, 5])
# Get the biggest value in the numpy array
max_b = b.max()
print(max_b)
# Get the smallest value in the numpy array

min_b = b.min()
print(min_b)

5
-1


##### Numpy Array Operations

In [31]:
u = np.array([1, 0])
v = np.array([0, 1])
# Numpy Array Addition
z = np.add(u, v)
z

array([1, 1])

In [32]:
a = np.array([10, 20, 30])
b = np.array([5, 10, 15])
# Numpy Array Subtraction
c = np.subtract(a, b)

print(c)

[ 5 10 15]
